#ifndef S840D_DEF_H
#define S840D_DEF_H

#define TYPE(DEF_TYPE) \
    DEF_TYPE(INT) \
    DEF_TYPE(REAL) \
    DEF_TYPE(BOOL) \
    DEF_TYPE(CHAR) \
    DEF_TYPE(STRING) \
//    DEF_TYPE(AXIS)
//    DEF_TYPE(FRAME)

#define G_COMMANDS(DEF_TYPE) \
    DEF_TYPE(CIP) \
    DEF_TYPE(ASPLINE) \
    DEF_TYPE(BSPLINE) \
    DEF_TYPE(CSPLINE) \
    DEF_TYPE(CT) \
    DEF_TYPE(POLY) \
    DEF_TYPE(INVCW) \
    DEF_TYPE(INVCCW) \
    DEF_TYPE(ROT) \
    DEF_TYPE(AROT) \
    DEF_TYPE(TRANS) \
    DEF_TYPE(ATRANS) \
    DEF_TYPE(SCALE) \
    DEF_TYPE(ASCALE) \
    DEF_TYPE(MIRROR) \
    DEF_TYPE(AMIRROR) \
    DEF_TYPE(ROTS) \
    DEF_TYPE(AROTS) \
    DEF_TYPE(STARTFIFO) \
    DEF_TYPE(STOPFIFO) \
    DEF_TYPE(FIFOCTRL) \
    DEF_TYPE(CFC) \
    DEF_TYPE(CFTCP) \
    DEF_TYPE(CFIN) \
    DEF_TYPE(NORM) \
    DEF_TYPE(KONT) \
    DEF_TYPE(KONTT) \
    DEF_TYPE(KONTC) \
    DEF_TYPE(SUPA) \
    DEF_TYPE(FFWOF) \
    DEF_TYPE(FFWON) \
    DEF_TYPE(DIAMOF) \
    DEF_TYPE(DIAMON) \
    DEF_TYPE(DIAM90) \
    DEF_TYPE(DIAMCYCOF) \
    DEF_TYPE(FNORM) \
    DEF_TYPE(FLIN) \
    DEF_TYPE(FCUB) \

#define ARITHMETIC_FUNC_1ARG(DEF_TYPE) \
    DEF_TYPE(SIN) \
    DEF_TYPE(COS) \
    DEF_TYPE(TAN) \
    DEF_TYPE(ASIN) \
    DEF_TYPE(ACOS) \
    DEF_TYPE(SQRT) \
    DEF_TYPE(ABS) \
    DEF_TYPE(POT) \
    DEF_TYPE(TRUNC) \
    DEF_TYPE(ROUND) \
    DEF_TYPE(LN) \
    DEF_TYPE(EXP)

#define ARITHMETIC_FUNC_2ARG(DEF_TYPE) \
    DEF_TYPE(ATAN2) \
    DEF_TYPE(MINVAL) \
    DEF_TYPE(MAXVAL)

#define GOTO_KEYWORDS(DEF_TYPE) \
    DEF_TYPE(GOTOB) \
    DEF_TYPE(GOTOF) \
    DEF_TYPE(GOTO) \
    DEF_TYPE(GOTOC)

#define COORD_TYPE(DEF_TYPE) \
    DEF_TYPE(AC) \
    DEF_TYPE(IC) \
    DEF_TYPE(DC) \
    DEF_TYPE(ACP) \
    DEF_TYPE(ACN)

#define DEF_TYPE_ENUM(name) name,
#define DEF_TYPE_STRING(name) #name,




#endif // S840D_DEF_H
